exports.ELEMENT_NODE = 1;
exports.ATTRIBUTE_NODE = 2;
exports.TEXT_NODE = 3;
exports.PROCESSING_INSTRUCTION_NODE = 7;
exports.COMMENT_NODE = 8;
exports.DOCUMENT_NODE = 9;
exports.DOCUMENT_TYPE_NODE = 10;
exports.DOCUMENT_FRAGMENT_NODE = 11;
